# Generated by Django 5.1.6 on 2025-03-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='logo_cat',
            field=models.FileField(null=True, upload_to='carreras'),
        ),
    ]
