# Generated by Django 5.1.6 on 2025-03-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0002_carrera_logo_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='logo_cat',
            new_name='logo_car',
        ),
    ]
