# Generated by Django 5.1.6 on 2025-03-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0003_rename_logo_cat_carrera_logo_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_cur', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_cur', models.CharField(max_length=50)),
                ('aula_cur', models.IntegerField()),
                ('fk_id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Educacion.carrera')),
            ],
        ),
    ]
